spring:
  profiles:
    active: dev
  jackson:
    serialization:
      INDENT_OUTPUT: true

# Logging Configuration
logging:
  level:
    root: INFO
    com.github.theoydr.eventmanagement: INFO
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

  api:
    include-payload: false


  # File Appender Configuration
  file:
    name: logs/event-management.log


  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7
      total-size-cap: 1GB
      file-name-pattern: logs/archived/event-management-%d{yyyy-MM-dd}-%i.log.gz





